name: Generator

on:
  issues:
  watch:
    types: [started]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python #安装python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install requirements #安装requests
      run: |
        pip install -r requirements.txt
    - name: Update links #更新
      run: |
        python generator/run.py
        echo `date +"%Y-%m-%d %H:%M:%S"` begin > generator/time.log
    - name: Commit & Push
      uses: action-x/commit@v2.9
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'main'
        force-push: 'true'
        rebase: 'true'
        commit-message: 'Generate Json'
        name: github-actions[bot]
        email: github-actions[bot]@users.noreply.github.com
